// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Orchestrator is an autogenerated mock type for the Orchestrator type
type Orchestrator struct {
	mock.Mock
}

type Orchestrator_Expecter struct {
	mock *mock.Mock
}

func (_m *Orchestrator) EXPECT() *Orchestrator_Expecter {
	return &Orchestrator_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewOrchestrator interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrchestrator creates a new instance of Orchestrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrchestrator(t mockConstructorTestingTNewOrchestrator) *Orchestrator {
	mock := &Orchestrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
