// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ClientsLedger is an autogenerated mock type for the ClientsLedger type
type ClientsLedger struct {
	mock.Mock
}

type ClientsLedger_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientsLedger) EXPECT() *ClientsLedger_Expecter {
	return &ClientsLedger_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewClientsLedger interface {
	mock.TestingT
	Cleanup(func())
}

// NewClientsLedger creates a new instance of ClientsLedger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClientsLedger(t mockConstructorTestingTNewClientsLedger) *ClientsLedger {
	mock := &ClientsLedger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
