// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NodesLedger is an autogenerated mock type for the NodesLedger type
type NodesLedger struct {
	mock.Mock
}

type NodesLedger_Expecter struct {
	mock *mock.Mock
}

func (_m *NodesLedger) EXPECT() *NodesLedger_Expecter {
	return &NodesLedger_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewNodesLedger interface {
	mock.TestingT
	Cleanup(func())
}

// NewNodesLedger creates a new instance of NodesLedger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNodesLedger(t mockConstructorTestingTNewNodesLedger) *NodesLedger {
	mock := &NodesLedger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
